# Generated by Django 2.1.1 on 2018-09-14 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CodigoBarra',
            field=models.CharField(max_length=50, verbose_name='Crachá'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=50, verbose_name='CPF'),
        ),
    ]
