# Generated by Django 2.1.1 on 2018-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180914_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='cpf',
        ),
        migrations.AddField(
            model_name='visitante',
            name='documento',
            field=models.CharField(default=0, max_length=50, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, help_text='(xx)xxxxx-xxxx', max_length=15),
        ),
        migrations.AddField(
            model_name='visitante',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Visitante'), (1, 'Lojista')], default=0),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CodigoBarra',
            field=models.CharField(blank=True, max_length=50, verbose_name='Crachá'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='aniversario',
            field=models.DateField(blank=True, verbose_name='aniversario'),
        ),
    ]
