# Generated by Django 2.1.1 on 2018-09-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('aniversario', models.DateField(verbose_name='aniversario')),
                ('sexo', models.PositiveSmallIntegerField(choices=[(0, 'Não Informado'), (1, 'Homem'), (2, 'Mulher')], default=0)),
                ('CodigoBarra', models.CharField(max_length=50)),
            ],
        ),
    ]
