# Generated by Django 2.1.1 on 2018-10-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20180914_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='impresso',
            field=models.BooleanField(default=False),
        ),
    ]
